# version: "3"

# services:
#   db:
#     image: postgres:11
#     ports:
#       - "5432:5432"
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=test_db
#   web:
#     build: .
#     # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
#     command: bash -c "cd app/ && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
#     volumes:
#       - .:/code
#     environment:
#       - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/test_db
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
version: '3.8'

services:

  web:
    build: .
    command: bash -c "cd app/ && uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    volumes:
      - .:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/test_db
    depends_on:
      - db

  db:
    image: postgres:15.3
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db